// Generated by GitHub Copilot
// Lectura mantenible de imágenes desde /public/images. Se ejecuta en build (Server Component).
import fs from 'node:fs';
import path from 'node:path';

const VALID_EXT = ['.jpg', '.jpeg', '.png', '.webp'];

/**
 * Lista las imágenes de una subcarpeta de /public/images.
 * @param folder Subcarpeta dentro de /public/images (ej: 'platos', 'restaurante').
 * @returns Array de rutas web absolutas (ej: '/images/platos/foto.jpg').
 */
export function listImages(folder: string): string[] {
  const dir = path.join(process.cwd(), 'public', 'images', folder);
  try {
    if (!fs.existsSync(dir)) return [];
    return fs
      .readdirSync(dir)
      .filter((f) => VALID_EXT.includes(path.extname(f).toLowerCase()))
      .sort()
      .map((f) => `/images/${folder}/${f}`);
  } catch {
    return [];
  }
}
