// Generated by GitHub Copilot
import type { Metadata } from 'next';
import Gallery from '@/components/Gallery';

export const metadata: Metadata = {
  title: 'Galería',
  description: 'Fotografías de los platos, salón y terraza del Restaurante Arolena.'
};

export default function GaleriaPage() {
  return <Gallery full />;
}
