// Generated by GitHub Copilot
import type { Metadata, Viewport } from 'next';
import { Fraunces, Outfit } from 'next/font/google';
import './globals.css';
import Header from '@/components/Header';
import Footer from '@/components/Footer';
import ScrollProgress from '@/components/ScrollProgress';
import CustomCursor from '@/components/CustomCursor';
import ChapterIndex from '@/components/ChapterIndex';
import { restaurantInfo } from '@/data/restaurantInfo';

const display = Fraunces({
  subsets: ['latin'],
  weight: ['300', '400', '500', '600', '700', '900'],
  style: ['normal', 'italic'],
  variable: '--font-display',
  display: 'swap',
  axes: ['SOFT', 'opsz']
});

const sans = Outfit({
  subsets: ['latin'],
  weight: ['300', '400', '500', '600'],
  variable: '--font-sans',
  display: 'swap'
});

const SITE_URL = process.env.NEXT_PUBLIC_SITE_URL || 'https://arolena.vercel.app';

export const metadata: Metadata = {
  metadataBase: new URL(SITE_URL),
  title: {
    default: 'Arolena | Restaurante mediterráneo, italiano y parrilla en Albolote',
    template: '%s | Arolena'
  },
  description:
    'Restaurante Arolena en Albolote, Granada. Cocina mediterránea e italiana, pizzas en horno de leña, parrilla, terraza, comida para llevar y reservas por WhatsApp.',
  keywords: [
    'Arolena',
    'restaurante Albolote',
    'restaurante Granada',
    'pizza horno de leña',
    'cocina mediterránea',
    'cocina italiana',
    'parrilla Albolote'
  ],
  applicationName: 'Arolena',
  authors: [{ name: 'Restaurante Arolena' }],
  alternates: { canonical: '/' },
  openGraph: {
    title: 'Arolena | Restaurante mediterráneo, italiano y parrilla en Albolote',
    description:
      'Cocina mediterránea e italiana, pizzas en horno de leña, parrilla y un ambiente elegante en Albolote, Granada.',
    url: SITE_URL,
    siteName: 'Arolena',
    locale: 'es_ES',
    type: 'website',
    images: [
      {
        url: '/images/restaurante/IMG_5232.jpeg',
        width: 1200,
        height: 630,
        alt: 'Restaurante Arolena en Albolote, Granada'
      }
    ]
  },
  twitter: {
    card: 'summary_large_image',
    title: 'Arolena | Restaurante en Albolote',
    description:
      'Cocina mediterránea e italiana, pizzas en horno de leña y parrilla en Albolote, Granada.',
    images: ['/images/restaurante/IMG_5232.jpeg']
  },
  robots: { index: true, follow: true },
  icons: {
    icon: [{ url: '/favicon.svg', type: 'image/svg+xml' }],
    shortcut: '/favicon.svg',
    apple: '/favicon.svg'
  }
};

export const viewport: Viewport = {
  themeColor: '#0a0a0a',
  width: 'device-width',
  initialScale: 1
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  const jsonLd = {
    '@context': 'https://schema.org',
    '@type': 'Restaurant',
    name: restaurantInfo.nombreCompleto,
    image: `${SITE_URL}/images/restaurante/IMG_5232.jpeg`,
    url: SITE_URL,
    telephone: restaurantInfo.telefonoTel,
    servesCuisine: ['Mediterránea', 'Italiana', 'Parrilla'],
    priceRange: '€€',
    address: {
      '@type': 'PostalAddress',
      streetAddress: 'Avenida Lucilo Carvajal 17',
      postalCode: '18220',
      addressLocality: 'Albolote',
      addressRegion: 'Granada',
      addressCountry: 'ES'
    },
    openingHoursSpecification: [
      {
        '@type': 'OpeningHoursSpecification',
        dayOfWeek: ['Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'],
        opens: '12:00',
        closes: '16:30'
      },
      {
        '@type': 'OpeningHoursSpecification',
        dayOfWeek: ['Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'],
        opens: '20:00',
        closes: '23:30'
      }
    ],
    sameAs: [restaurantInfo.instagram, restaurantInfo.tiktok]
  };

  return (
    <html lang="es" className={`${display.variable} ${sans.variable}`}>
      <body className="font-sans">
        <a
          href="#main"
          className="sr-only focus:not-sr-only focus:fixed focus:top-3 focus:left-3 focus:z-[100] focus:px-4 focus:py-2 focus:bg-arolena-gold focus:text-arolena-black focus:rounded"
        >
          Saltar al contenido principal
        </a>
        {/* Grain texture overlay */}
        <div aria-hidden="true" className="grain-overlay" />
        <ScrollProgress />
        <CustomCursor />
        <ChapterIndex />
        <Header />
        <main id="main">{children}</main>
        <Footer />
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }}
        />
      </body>
    </html>
  );
}
