// Generated by GitHub Copilot
import Hero from '@/components/Hero';
import WoodOvenSection from '@/components/WoodOvenSection';
import CuisineSection from '@/components/CuisineSection';
import OccasionsSection from '@/components/OccasionsSection';
import Gallery from '@/components/Gallery';
import ServicesSection from '@/components/ServicesSection';
import ContactSection from '@/components/ContactSection';
import MenuSection from '@/components/MenuSection';

export default function HomePage() {
  return (
    <>
      <Hero />
      <WoodOvenSection />
      <CuisineSection />
      <OccasionsSection />
      <Gallery />
      <ServicesSection />
      <MenuSection />
      <ContactSection />
    </>
  );
}
