// Generated by GitHub Copilot
import Hero from '@/components/Hero';
import Marquee from '@/components/Marquee';
import WoodOvenSection from '@/components/WoodOvenSection';
import CuisineSection from '@/components/CuisineSection';
import PhilosophySection from '@/components/PhilosophySection';
import OccasionsSection from '@/components/OccasionsSection';
import Gallery from '@/components/Gallery';
import ServicesSection from '@/components/ServicesSection';
import ContactSection from '@/components/ContactSection';
import MenuSection from '@/components/MenuSection';
import OrnamentalDivider from '@/components/OrnamentalDivider';

const MARQUEE_ITEMS = [
  'Horno de leña',
  'Masa artesanal',
  'Parrilla',
  'Cocina mediterránea',
  'Sabores italianos',
  'Albolote · Granada'
];

export default function HomePage() {
  return (
    <>
      <Hero />
      <Marquee items={MARQUEE_ITEMS} />
      <WoodOvenSection />
      <CuisineSection />
      <PhilosophySection />
      <OccasionsSection />
      <OrnamentalDivider />
      <Gallery />
      <ServicesSection />
      <MenuSection />
      <ContactSection />
    </>
  );
}
