// Generated by GitHub Copilot
import type { Metadata } from 'next';
import MenuSection from '@/components/MenuSection';

export const metadata: Metadata = {
  title: 'Carta',
  description:
    'Carta completa del Restaurante Arolena: entrantes, ensaladas, pastas, pizzas en horno de leña, carnes, pescados y postres caseros.'
};

export default function CartaPage() {
  return <MenuSection full />;
}
