// Generated by GitHub Copilot
// Índice lateral de capítulos con scroll-spy. Visible solo en pantallas grandes.
'use client';

import { useEffect, useState } from 'react';

const chapters = [
  { id: 'horno', num: 'I', label: 'La casa' },
  { id: 'cocina', num: 'II', label: 'La cocina' },
  { id: 'ocasiones', num: 'III', label: 'El espacio' },
  { id: 'galeria', num: 'IV', label: 'Galería' },
  { id: 'servicios', num: 'V', label: 'Servicios' },
  { id: 'carta', num: 'VI', label: 'Carta' },
  { id: 'contacto', num: 'VII', label: 'Reservas' }
];

export default function ChapterIndex() {
  const [active, setActive] = useState<string>('horno');

  useEffect(() => {
    const observer = new IntersectionObserver(
      (entries) => {
        entries.forEach((entry) => {
          if (entry.isIntersecting) setActive(entry.target.id);
        });
      },
      { rootMargin: '-40% 0px -55% 0px', threshold: 0 }
    );
    chapters.forEach((c) => {
      const el = document.getElementById(c.id);
      if (el) observer.observe(el);
    });
    return () => observer.disconnect();
  }, []);

  return (
    <nav
      aria-label="Capítulos"
      className="hidden xl:flex fixed left-6 top-1/2 -translate-y-1/2 z-40 flex-col gap-3"
    >
      {chapters.map((c) => {
        const isActive = active === c.id;
        return (
          <a
            key={c.id}
            href={`#${c.id}`}
            className="group flex items-center gap-3 text-[10px] tracking-[0.3em] uppercase text-arolena-cream/40 hover:text-arolena-gold transition-colors"
          >
            <span
              className={`inline-block h-px transition-all duration-500 ${
                isActive ? 'w-12 bg-arolena-gold' : 'w-4 bg-arolena-cream/40 group-hover:w-8 group-hover:bg-arolena-gold'
              }`}
            />
            <span className={isActive ? 'text-arolena-gold' : ''}>
              <span className="font-display-italic mr-2 normal-case tracking-normal text-sm">
                {c.num}.
              </span>
              {c.label}
            </span>
          </a>
        );
      })}
    </nav>
  );
}
