// Generated by GitHub Copilot
import Eyebrow from './Eyebrow';
import { restaurantInfo } from '@/data/restaurantInfo';

export default function ContactSection() {
  return (
    <section id="contacto" className="bg-arolena-ink py-24 md:py-36">
      <div className="container grid lg:grid-cols-2 gap-12 lg:gap-16">
        <div>
          <Eyebrow number="07">Contacto y reservas</Eyebrow>
          <h2 className="font-display text-5xl md:text-6xl text-arolena-cream leading-[0.95]">
            Reserva tu{' '}
            <span className="font-display-italic text-arolena-gold">mesa</span>.
          </h2>
          <p className="mt-4 text-arolena-cream/80 leading-relaxed">
            Reserva tu mesa por teléfono o WhatsApp. Indícanos el día, la hora,
            el número de personas y si prefieres interior o terraza.
          </p>

          <div className="mt-8 flex flex-wrap gap-3">
            <a
              href={restaurantInfo.whatsappLink}
              target="_blank"
              rel="noopener noreferrer"
              className="inline-flex items-center gap-2 px-6 py-3 rounded-full bg-arolena-gold text-arolena-black font-medium hover:bg-arolena-goldsoft transition-colors"
            >
              Reservar por WhatsApp
            </a>
            <a
              href={`tel:${restaurantInfo.telefonoTel}`}
              className="inline-flex items-center gap-2 px-6 py-3 rounded-full border border-arolena-cream/40 text-arolena-cream hover:border-arolena-gold hover:text-arolena-gold transition-colors"
            >
              Llamar {restaurantInfo.telefono}
            </a>
          </div>

          <dl className="mt-10 space-y-5 text-arolena-cream/85">
            <div>
              <dt className="text-arolena-gold text-xs uppercase tracking-[0.25em]">
                Dirección
              </dt>
              <dd className="mt-1">
                <a
                  href={restaurantInfo.mapsLink}
                  target="_blank"
                  rel="noopener noreferrer"
                  className="hover:text-arolena-gold underline-offset-4 hover:underline"
                >
                  {restaurantInfo.direccion}
                </a>
              </dd>
            </div>
            <div>
              <dt className="text-arolena-gold text-xs uppercase tracking-[0.25em]">
                Horario
              </dt>
              <dd className="mt-1">
                Comidas {restaurantInfo.horario.comidas} · Cenas{' '}
                {restaurantInfo.horario.cenas}
                <br />
                {restaurantInfo.horario.cierre}
              </dd>
            </div>
            <div>
              <dt className="text-arolena-gold text-xs uppercase tracking-[0.25em]">
                Teléfono
              </dt>
              <dd className="mt-1">
                <a
                  href={`tel:${restaurantInfo.telefonoTel}`}
                  className="hover:text-arolena-gold"
                >
                  {restaurantInfo.telefono}
                </a>
              </dd>
            </div>
            <div>
              <dt className="text-arolena-gold text-xs uppercase tracking-[0.25em]">
                Aparcamiento
              </dt>
              <dd className="mt-1">
                Facilidad de aparcamiento en los alrededores. A pocos minutos
                de Granada capital.
              </dd>
            </div>
            <div>
              <dt className="text-arolena-gold text-xs uppercase tracking-[0.25em]">
                Redes
              </dt>
              <dd className="mt-1 flex flex-wrap gap-4">
                <a
                  href={restaurantInfo.instagram}
                  target="_blank"
                  rel="noopener noreferrer"
                  className="hover:text-arolena-gold"
                >
                  Instagram {restaurantInfo.instagramHandle}
                </a>
                <a
                  href={restaurantInfo.tiktok}
                  target="_blank"
                  rel="noopener noreferrer"
                  className="hover:text-arolena-gold"
                >
                  TikTok {restaurantInfo.tiktokHandle}
                </a>
              </dd>
            </div>
          </dl>
        </div>

        <div className="rounded-2xl overflow-hidden border border-arolena-line min-h-[360px]">
          <iframe
            src={restaurantInfo.mapsEmbed}
            title="Ubicación del Restaurante Arolena en Google Maps"
            loading="lazy"
            referrerPolicy="no-referrer-when-downgrade"
            className="w-full h-full min-h-[360px] border-0"
          />
        </div>
      </div>
    </section>
  );
}
