// Generated by GitHub Copilot
import Link from 'next/link';
import type { ReactNode } from 'react';

type Variant = 'primary' | 'secondary' | 'ghost';

interface CTAButtonProps {
  href: string;
  children: ReactNode;
  variant?: Variant;
  external?: boolean;
  ariaLabel?: string;
  className?: string;
}

const styles: Record<Variant, string> = {
  primary:
    'bg-arolena-gold text-arolena-black hover:bg-arolena-goldsoft focus-visible:outline-arolena-gold',
  secondary:
    'bg-transparent text-arolena-cream border border-arolena-cream/40 hover:border-arolena-gold hover:text-arolena-gold focus-visible:outline-arolena-gold',
  ghost:
    'bg-transparent text-arolena-cream/90 hover:text-arolena-gold focus-visible:outline-arolena-gold'
};

/**
 * Botón CTA reutilizable. Maneja enlaces internos (Link) y externos (a target=_blank).
 * Mantiene foco visible accesible (WCAG 2.2 AA).
 */
export default function CTAButton({
  href,
  children,
  variant = 'primary',
  external = false,
  ariaLabel,
  className = ''
}: CTAButtonProps) {
  const base =
    'inline-flex items-center justify-center gap-2 px-6 py-3 rounded-full text-sm md:text-base font-medium tracking-wide transition-colors focus:outline-none focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-4';
  const cls = `${base} ${styles[variant]} ${className}`;

  if (external) {
    return (
      <a
        href={href}
        target="_blank"
        rel="noopener noreferrer"
        aria-label={ariaLabel}
        className={cls}
      >
        {children}
      </a>
    );
  }
  return (
    <Link href={href} aria-label={ariaLabel} className={cls}>
      {children}
    </Link>
  );
}
