// Generated by GitHub Copilot
const pillars = [
  {
    titulo: 'Mediterránea',
    descripcion:
      'Productos frescos, aceite de oliva y recetas que celebran el sabor del mar y la huerta.'
  },
  {
    titulo: 'Italiana',
    descripcion:
      'Pastas, lasañas, risotos y pizzas artesanales horneadas en horno de leña.'
  },
  {
    titulo: 'Parrilla',
    descripcion:
      'Carnes seleccionadas y pescados a la brasa con el punto justo en cada bocado.'
  }
];

export default function CuisineSection() {
  return (
    <section id="cocina" className="bg-arolena-black py-20 md:py-28">
      <div className="container">
        <div className="max-w-3xl">
          <span aria-hidden="true" className="gold-rule" />
          <p className="text-arolena-gold tracking-[0.3em] text-xs uppercase mb-4">
            Nuestra cocina
          </p>
          <h2 className="font-display text-4xl md:text-5xl text-arolena-cream">
            Tres pilares, una sola pasión
          </h2>
          <p className="mt-6 text-arolena-cream/80 text-lg leading-relaxed">
            Una carta variada pensada para todos los gustos: pizzas, pastas,
            carnes, pescados, ensaladas, postres caseros y propuestas para
            compartir.
          </p>
        </div>

        <div className="mt-12 grid md:grid-cols-3 gap-6">
          {pillars.map((p) => (
            <article
              key={p.titulo}
              className="card-hover rounded-2xl border border-arolena-line bg-arolena-ink p-8"
            >
              <h3 className="font-display text-2xl text-arolena-cream">
                {p.titulo}
              </h3>
              <p className="mt-4 text-arolena-cream/75 leading-relaxed">
                {p.descripcion}
              </p>
            </article>
          ))}
        </div>
      </div>
    </section>
  );
}
