// Generated by GitHub Copilot
import Eyebrow from './Eyebrow';

const pillars = [
  {
    num: 'I',
    titulo: 'Mediterránea',
    descripcion:
      'Productos frescos, aceite de oliva y recetas que celebran el sabor del mar y la huerta.'
  },
  {
    num: 'II',
    titulo: 'Italiana',
    descripcion:
      'Pastas, lasañas, risotos y pizzas artesanales horneadas en horno de leña.'
  },
  {
    num: 'III',
    titulo: 'Parrilla',
    descripcion:
      'Carnes seleccionadas y pescados a la brasa con el punto justo en cada bocado.'
  }
];

export default function CuisineSection() {
  return (
    <section id="cocina" className="relative bg-arolena-black py-24 md:py-36">
      <div className="container">
        <div className="max-w-3xl">
          <Eyebrow number="02">Nuestra cocina</Eyebrow>
          <h2 className="font-display text-5xl md:text-6xl text-arolena-cream leading-[0.95]">
            Tres pilares,{' '}
            <span className="font-display-italic text-arolena-gold">una sola pasión</span>.
          </h2>
          <p className="mt-8 text-arolena-cream/75 text-lg leading-relaxed max-w-2xl">
            Una carta variada pensada para todos los gustos: pizzas, pastas,
            carnes, pescados, ensaladas, postres caseros y propuestas para
            compartir.
          </p>
        </div>

        <div className="mt-16 grid md:grid-cols-3 gap-px bg-arolena-line">
          {pillars.map((p) => (
            <article
              key={p.titulo}
              className="card-hover bg-arolena-ink p-10 md:p-12 group"
            >
              <span className="font-display-italic text-arolena-gold/70 text-2xl block mb-8">
                — {p.num}
              </span>
              <h3 className="font-display text-3xl text-arolena-cream group-hover:text-arolena-gold transition-colors">
                {p.titulo}
              </h3>
              <p className="mt-5 text-arolena-cream/70 leading-relaxed">
                {p.descripcion}
              </p>
              <span className="block mt-8 w-8 h-px bg-arolena-gold/40 group-hover:w-16 group-hover:bg-arolena-gold transition-all duration-500" />
            </article>
          ))}
        </div>
      </div>
    </section>
  );
}
