// Generated by GitHub Copilot
// Cursor dorado personalizado con punto interior. Solo en pantallas con puntero fino.
'use client';

import { useEffect, useState } from 'react';

export default function CustomCursor() {
  const [pos, setPos] = useState({ x: -100, y: -100 });
  const [hovering, setHovering] = useState(false);
  const [enabled, setEnabled] = useState(false);

  useEffect(() => {
    const mq = window.matchMedia('(pointer: fine)');
    setEnabled(mq.matches);
    const onChange = () => setEnabled(mq.matches);
    mq.addEventListener('change', onChange);
    return () => mq.removeEventListener('change', onChange);
  }, []);

  useEffect(() => {
    if (!enabled) return;
    const move = (e: MouseEvent) => setPos({ x: e.clientX, y: e.clientY });
    const over = (e: MouseEvent) => {
      const t = e.target as HTMLElement | null;
      const interactive = !!t?.closest('a, button, [role="button"], input, textarea, select, label');
      setHovering(interactive);
    };
    window.addEventListener('mousemove', move);
    window.addEventListener('mouseover', over);
    return () => {
      window.removeEventListener('mousemove', move);
      window.removeEventListener('mouseover', over);
    };
  }, [enabled]);

  if (!enabled) return null;

  return (
    <div
      aria-hidden="true"
      className="pointer-events-none fixed inset-0 z-[70]"
    >
      {/* Anillo grande */}
      <div
        className="absolute rounded-full border border-arolena-gold transition-[width,height,opacity] duration-200"
        style={{
          width: hovering ? 56 : 28,
          height: hovering ? 56 : 28,
          left: pos.x - (hovering ? 28 : 14),
          top: pos.y - (hovering ? 28 : 14),
          opacity: 0.85
        }}
      />
      {/* Punto interior */}
      <div
        className="absolute w-1 h-1 rounded-full bg-arolena-gold"
        style={{ left: pos.x - 2, top: pos.y - 2 }}
      />
    </div>
  );
}
