// Generated by GitHub Copilot
// Etiqueta estilo revista: número + barra + texto. Aporta jerarquía editorial.
interface EyebrowProps {
  number: string;
  children: React.ReactNode;
}

export default function Eyebrow({ number, children }: EyebrowProps) {
  return (
    <p className="eyebrow mb-6">
      <span className="num">{number}</span>
      <span aria-hidden="true" className="bar" />
      <span>{children}</span>
    </p>
  );
}
