// Generated by GitHub Copilot
import Logo from './Logo';
import { restaurantInfo } from '@/data/restaurantInfo';

export default function Footer() {
  const year = new Date().getFullYear();
  return (
    <footer className="bg-arolena-black border-t border-arolena-line py-12">
      <div className="container grid md:grid-cols-3 gap-8 text-arolena-cream/80 text-sm">
        <div>
          <div className="flex items-center gap-3 text-arolena-cream">
            <Logo className="h-7 w-7 text-arolena-gold" />
            <span className="font-display text-xl tracking-wider">Arolena</span>
          </div>
          <p className="mt-4 leading-relaxed">
            {restaurantInfo.nombreCompleto}. Cocina mediterránea e italiana,
            horno de leña y parrilla en {restaurantInfo.ciudad}.
          </p>
        </div>

        <div>
          <h3 className="text-arolena-gold text-xs uppercase tracking-[0.25em] mb-4">
            Contacto
          </h3>
          <p>{restaurantInfo.direccion}</p>
          <p className="mt-2">
            <a href={`tel:${restaurantInfo.telefonoTel}`} className="hover:text-arolena-gold">
              {restaurantInfo.telefono}
            </a>
          </p>
          <p className="mt-2">
            <a
              href={restaurantInfo.whatsappLink}
              target="_blank"
              rel="noopener noreferrer"
              className="hover:text-arolena-gold"
            >
              WhatsApp {restaurantInfo.whatsappDisplay}
            </a>
          </p>
        </div>

        <div>
          <h3 className="text-arolena-gold text-xs uppercase tracking-[0.25em] mb-4">
            Horario
          </h3>
          <p>Comidas: {restaurantInfo.horario.comidas}</p>
          <p>Cenas: {restaurantInfo.horario.cenas}</p>
          <p className="mt-2">{restaurantInfo.horario.cierre}</p>
          <div className="mt-4 flex gap-4">
            <a
              href={restaurantInfo.instagram}
              target="_blank"
              rel="noopener noreferrer"
              className="hover:text-arolena-gold"
            >
              Instagram
            </a>
            <a
              href={restaurantInfo.tiktok}
              target="_blank"
              rel="noopener noreferrer"
              className="hover:text-arolena-gold"
            >
              TikTok
            </a>
          </div>
        </div>
      </div>

      <div className="container mt-10 pt-6 border-t border-arolena-line text-arolena-cream/55 text-xs flex flex-col sm:flex-row sm:justify-between gap-2">
        <p>© {year} {restaurantInfo.nombreCompleto}. Todos los derechos reservados.</p>
        <p>Hecho con cariño en {restaurantInfo.ciudad}.</p>
      </div>
    </footer>
  );
}
