// Generated by GitHub Copilot
import Image from 'next/image';
import { listImages } from '@/lib/getImages';
import Eyebrow from './Eyebrow';

interface GalleryProps {
  /** Si true, muestra todas las imágenes. Si false, recorte para Home. */
  full?: boolean;
}

/**
 * Galería responsive en grid. Lee imágenes desde /public/images/{platos,restaurante}.
 * Lazy loading nativo via next/image.
 */
export default function Gallery({ full = false }: GalleryProps) {
  const platos = listImages('platos');
  const restaurante = listImages('restaurante');
  const todas = [...platos, ...restaurante];
  const items = full ? todas : todas.slice(0, 8);

  return (
    <section id="galeria" className="bg-arolena-ink py-20 md:py-28">
      <div className="container">
        <div className="max-w-3xl mb-14">
          <Eyebrow number="04">Galería</Eyebrow>
          <h2 className="font-display text-5xl md:text-6xl text-arolena-cream leading-[0.95]">
            Mira Arolena{' '}
            <span className="font-display-italic text-arolena-gold">por dentro</span>.
          </h2>
          <p className="mt-6 text-arolena-cream/75 max-w-xl">
            Platos, salón y terraza. Una muestra del ambiente que te espera.
          </p>
        </div>

        {items.length === 0 ? (
          <div className="rounded-2xl border border-dashed border-arolena-line p-12 text-center text-arolena-cream/70">
            <p className="font-medium">Galería preparada.</p>
            <p className="mt-2 text-sm">
              Para añadir imágenes, copia los archivos en{' '}
              <code className="text-arolena-gold">/public/images/platos/</code>{' '}
              o{' '}
              <code className="text-arolena-gold">
                /public/images/restaurante/
              </code>{' '}
              y vuelve a desplegar.
            </p>
          </div>
        ) : (
          <ul className="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-3 md:gap-4">
            {items.map((src, i) => (
              <li
                key={src}
                className="relative aspect-square overflow-hidden rounded-xl border border-arolena-line bg-arolena-black"
              >
                <Image
                  src={src}
                  alt={`Imagen ${i + 1} de Restaurante Arolena`}
                  fill
                  sizes="(min-width: 1024px) 25vw, (min-width: 768px) 33vw, 50vw"
                  loading="lazy"
                  className="object-cover editorial-img"
                />
              </li>
            ))}
          </ul>
        )}

        {!full && todas.length > items.length && (
          <div className="mt-10 text-center">
            <a
              href="/galeria"
              className="inline-flex items-center gap-2 px-6 py-3 rounded-full border border-arolena-cream/40 text-arolena-cream hover:border-arolena-gold hover:text-arolena-gold transition-colors"
            >
              Ver galería completa
            </a>
          </div>
        )}
      </div>
    </section>
  );
}
