// Generated by GitHub Copilot
'use client';

import Link from 'next/link';
import { useState } from 'react';
import Logo from './Logo';
import { restaurantInfo } from '@/data/restaurantInfo';

const nav = [
  { href: '/#horno', label: 'Horno de leña' },
  { href: '/#cocina', label: 'Nuestra cocina' },
  { href: '/carta', label: 'Carta' },
  { href: '/galeria', label: 'Galería' },
  { href: '/#servicios', label: 'Servicios' },
  { href: '/#contacto', label: 'Contacto' }
];

export default function Header() {
  const [open, setOpen] = useState(false);

  return (
    <header className="sticky top-0 z-50 bg-arolena-black/80 backdrop-blur-md border-b border-arolena-line/60">
      <div className="container flex items-center justify-between h-16 md:h-[72px]">
        <Link
          href="/"
          className="flex items-center gap-3 text-arolena-cream hover:text-arolena-gold transition-colors focus:outline-none focus-visible:outline focus-visible:outline-2 focus-visible:outline-arolena-gold rounded"
          aria-label={`${restaurantInfo.nombreComercial} - Inicio`}
        >
          <Logo className="h-7 w-7 text-arolena-gold" />
          <span className="font-display text-xl md:text-2xl tracking-wide">
            Arolena
          </span>
          <span className="hidden md:inline-block ml-2 pl-3 border-l border-arolena-line/80 text-[10px] tracking-[0.3em] uppercase text-arolena-cream/55">
            Albolote · Granada
          </span>
        </Link>

        <nav aria-label="Principal" className="hidden lg:block">
          <ul className="flex items-center gap-7 text-[12px] tracking-[0.2em] uppercase text-arolena-cream/75">
            {nav.map((n) => (
              <li key={n.href}>
                <Link
                  href={n.href}
                  className="hover:text-arolena-gold transition-colors focus:outline-none focus-visible:outline focus-visible:outline-2 focus-visible:outline-arolena-gold rounded py-1"
                >
                  {n.label}
                </Link>
              </li>
            ))}
          </ul>
        </nav>

        <a
          href={restaurantInfo.whatsappLink}
          target="_blank"
          rel="noopener noreferrer"
          className="hidden md:inline-flex items-center gap-2 px-4 py-2 rounded-full bg-arolena-gold text-arolena-black text-sm font-medium hover:bg-arolena-goldsoft transition-colors focus:outline-none focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-4 focus-visible:outline-arolena-gold"
        >
          <span className="font-display-italic">Reservar</span>
          <span aria-hidden="true">→</span>
        </a>

        <button
          type="button"
          onClick={() => setOpen((v) => !v)}
          aria-label={open ? 'Cerrar menú' : 'Abrir menú'}
          aria-expanded={open}
          aria-controls="menu-mobile"
          className="lg:hidden text-arolena-cream p-2 focus:outline-none focus-visible:outline focus-visible:outline-2 focus-visible:outline-arolena-gold rounded"
        >
          <svg width="24" height="24" viewBox="0 0 24 24" aria-hidden="true">
            {open ? (
              <path d="M6 6l12 12M18 6L6 18" stroke="currentColor" strokeWidth="2" />
            ) : (
              <path d="M4 7h16M4 12h16M4 17h16" stroke="currentColor" strokeWidth="2" />
            )}
          </svg>
        </button>
      </div>

      {open && (
        <nav
          id="menu-mobile"
          aria-label="Menú móvil"
          className="lg:hidden border-t border-arolena-line bg-arolena-black"
        >
          <ul className="container py-4 flex flex-col gap-1">
            {nav.map((n) => (
              <li key={n.href}>
                <Link
                  href={n.href}
                  onClick={() => setOpen(false)}
                  className="block py-3 text-arolena-cream hover:text-arolena-gold border-b border-arolena-line/60"
                >
                  {n.label}
                </Link>
              </li>
            ))}
            <li>
              <a
                href={restaurantInfo.whatsappLink}
                target="_blank"
                rel="noopener noreferrer"
                className="mt-3 inline-flex w-full justify-center px-4 py-3 rounded-full bg-arolena-gold text-arolena-black font-medium"
              >
                Reservar por WhatsApp
              </a>
            </li>
          </ul>
        </nav>
      )}
    </header>
  );
}
