// Generated by GitHub Copilot
import Image from 'next/image';
import CTAButton from './CTAButton';
import { restaurantInfo } from '@/data/restaurantInfo';

const HERO_IMAGE = '/images/restaurante/IMG_5232.jpeg';

export default function Hero() {
  return (
    <section className="relative isolate overflow-hidden bg-arolena-black">
      <div className="absolute inset-0 -z-10">
        <Image
          src={HERO_IMAGE}
          alt="Ambiente del Restaurante Arolena en Albolote"
          fill
          priority
          sizes="100vw"
          className="object-cover opacity-40"
        />
        <div className="absolute inset-0 bg-gradient-to-b from-arolena-black/70 via-arolena-black/60 to-arolena-black" />
      </div>

      <div className="container py-24 md:py-36 lg:py-44 text-center">
        <p className="text-arolena-gold tracking-[0.4em] text-xs md:text-sm uppercase mb-6">
          {restaurantInfo.ciudad}
        </p>
        <h1 className="font-display text-5xl md:text-7xl lg:text-8xl text-arolena-cream tracking-wide">
          Arolena
        </h1>
        <p className="mt-6 text-xl md:text-2xl text-arolena-cream/90 font-light">
          Sabores mediterráneos con horno de leña y parrilla.
        </p>
        <p className="mt-5 max-w-2xl mx-auto text-arolena-cream/75 leading-relaxed">
          Cocina mediterránea e italiana, pizzas de masa artesanal, carnes a la
          parrilla y un ambiente elegante para disfrutar en cualquier ocasión.
        </p>

        <div className="mt-10 flex flex-wrap items-center justify-center gap-3 md:gap-4">
          <CTAButton href="/carta" variant="primary">
            Ver carta
          </CTAButton>
          <CTAButton
            href={restaurantInfo.whatsappLink}
            external
            variant="secondary"
          >
            Reservar por WhatsApp
          </CTAButton>
          <CTAButton href={restaurantInfo.mapsLink} external variant="ghost">
            Cómo llegar
          </CTAButton>
        </div>
      </div>
    </section>
  );
}
