// Generated by GitHub Copilot
// Logo SVG minimalista inspirado en un horno de leña con llama interior.
type LogoProps = { className?: string; title?: string };

export default function Logo({ className = 'h-8 w-auto', title = 'Arolena' }: LogoProps) {
  return (
    <svg
      viewBox="0 0 48 48"
      className={className}
      role="img"
      aria-label={title}
      xmlns="http://www.w3.org/2000/svg"
    >
      <title>{title}</title>
      {/* Cúpula del horno */}
      <path
        d="M6 30c0-10 8-18 18-18s18 8 18 18v4H6v-4z"
        fill="none"
        stroke="currentColor"
        strokeWidth="2"
      />
      {/* Boca del horno */}
      <path
        d="M16 30c0-4.4 3.6-8 8-8s8 3.6 8 8v4H16v-4z"
        fill="currentColor"
        opacity="0.15"
        stroke="currentColor"
        strokeWidth="1.5"
      />
      {/* Llama */}
      <path
        d="M24 26c-1.6 1.6-2.4 3-2.4 4.4 0 1.6 1.1 2.6 2.4 2.6s2.4-1 2.4-2.6c0-1.4-.8-2.8-2.4-4.4z"
        fill="currentColor"
      />
      {/* Base */}
      <rect x="4" y="34" width="40" height="3" fill="currentColor" />
    </svg>
  );
}
