// Generated by GitHub Copilot
// Marquee infinito estilo editorial: ticker dorado entre secciones.
interface MarqueeProps {
  items: string[];
  separator?: string;
}

export default function Marquee({ items, separator = '✦' }: MarqueeProps) {
  // Duplicamos items para loop infinito sin saltos
  const loop = [...items, ...items];
  return (
    <div
      aria-hidden="true"
      className="overflow-hidden border-y border-arolena-line bg-arolena-black py-5"
    >
      <div className="marquee-track animate-marquee">
        {loop.map((item, i) => (
          <span
            key={i}
            className="font-display-italic text-3xl md:text-4xl text-arolena-cream/90 mx-8 whitespace-nowrap"
          >
            {item}
            <span className="text-arolena-gold mx-8">{separator}</span>
          </span>
        ))}
      </div>
    </div>
  );
}
