// Generated by GitHub Copilot
import menuData from '@/data/menu.json';
import type { Menu } from '@/data/menu.types';
import Link from 'next/link';
import Eyebrow from './Eyebrow';

const menu = menuData as Menu;

interface MenuSectionProps {
  /** Si true, muestra todas las categorías. Si false, vista resumida con CTA. */
  full?: boolean;
}

export default function MenuSection({ full = false }: MenuSectionProps) {
  const categorias = menu.carta;

  return (
    <section id="carta" className="bg-arolena-black py-24 md:py-36">
      <div className="container">
        <div className="flex flex-col md:flex-row md:items-end md:justify-between gap-6 mb-14">
          <div>
            <Eyebrow number="06">Carta</Eyebrow>
            <h2 className="font-display text-5xl md:text-6xl text-arolena-cream leading-[0.95]">
              Nuestra{' '}
              <span className="font-display-italic text-arolena-gold">carta</span>.
            </h2>
            <p className="mt-6 text-arolena-cream/75 max-w-xl">
              Una selección amplia para todos los gustos. Precios con IVA
              incluido.
            </p>
          </div>
          {full && (
            <nav aria-label="Categorías de la carta" className="flex flex-wrap gap-2">
              {categorias.map((c) => (
                <a
                  key={c.categoria}
                  href={`#cat-${slug(c.categoria)}`}
                  className="text-xs px-3 py-2 rounded-full border border-arolena-line text-arolena-cream/85 hover:border-arolena-gold hover:text-arolena-gold transition-colors"
                >
                  {c.categoria}
                </a>
              ))}
            </nav>
          )}
        </div>

        <div className="grid md:grid-cols-2 gap-x-12 gap-y-12">
          {categorias.map((cat) => (
            <article
              key={cat.categoria}
              id={`cat-${slug(cat.categoria)}`}
              className="scroll-mt-24"
            >
              <h3 className="font-display-italic text-3xl text-arolena-gold border-b border-arolena-line pb-3 mb-5">
                {cat.categoria}
              </h3>
              <ul className="divide-y divide-arolena-line/60">
                {cat.items.map((item) => (
                  <li
                    key={`${cat.categoria}-${item.nombre}`}
                    className="py-3 flex items-baseline gap-4"
                  >
                    <span className="text-arolena-cream">{item.nombre}</span>
                    <span
                      aria-hidden="true"
                      className="flex-1 border-b border-dotted border-arolena-line/70 translate-y-[-3px]"
                    />
                    {item.precio ? (
                      <span className="text-arolena-cream/90 font-medium whitespace-nowrap">
                        {item.precio}
                      </span>
                    ) : item.descripcion ? (
                      <span className="text-arolena-cream/70 text-sm text-right max-w-[60%]">
                        {item.descripcion}
                      </span>
                    ) : null}
                  </li>
                ))}
              </ul>
            </article>
          ))}
        </div>

        {!full && (
          <div className="mt-12 text-center">
            <Link
              href="/carta"
              className="inline-flex items-center gap-2 px-6 py-3 rounded-full bg-arolena-gold text-arolena-black font-medium hover:bg-arolena-goldsoft transition-colors focus:outline-none focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-4 focus-visible:outline-arolena-gold"
            >
              Ver carta completa
            </Link>
          </div>
        )}
      </div>
    </section>
  );
}

function slug(s: string): string {
  return s
    .toLowerCase()
    .normalize('NFD')
    .replace(/[\u0300-\u036f]/g, '')
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/(^-|-$)/g, '');
}
