// Generated by GitHub Copilot
import Image from 'next/image';
import Eyebrow from './Eyebrow';

const IMG = '/images/restaurante/IMG_2125.jpeg';

const ocasiones = [
  'Cenas en pareja',
  'Comidas familiares',
  'Grupos',
  'Reuniones de amigos',
  'Celebraciones',
  'Eventos',
  'Comidas de empresa'
];

export default function OccasionsSection() {
  return (
    <section id="ocasiones" className="relative bg-arolena-ink py-24 md:py-36 overflow-hidden">
      <span
        aria-hidden="true"
        className="absolute -left-8 top-12 text-[18rem] md:text-[28rem] leading-none font-display-italic text-arolena-cream/[0.025] select-none pointer-events-none"
      >
        03
      </span>

      <div className="container relative grid lg:grid-cols-12 gap-10 lg:gap-16 items-center">
        <div className="lg:col-span-5 lg:order-1 order-2">
          <Eyebrow number="03">Para cualquier ocasión</Eyebrow>
          <h2 className="font-display text-5xl md:text-6xl text-arolena-cream leading-[0.95]">
            Un espacio{' '}
            <span className="font-display-italic text-arolena-gold">versátil</span>{' '}
            y elegante.
          </h2>

          <blockquote className="pull-quote mt-10 max-w-md text-arolena-cream/85 font-display-italic text-xl leading-relaxed">
            Desde una comida informal hasta una ocasión especial, Arolena
            ofrece un espacio cómodo, elegante y versátil para disfrutar en
            buena compañía.
          </blockquote>

          <ul className="mt-10 flex flex-wrap gap-2">
            {ocasiones.map((o) => (
              <li
                key={o}
                className="text-xs px-4 py-2 rounded-full border border-arolena-line text-arolena-cream/85 hover:border-arolena-gold hover:text-arolena-gold transition-colors cursor-default"
              >
                {o}
              </li>
            ))}
          </ul>
        </div>

        <div className="lg:col-span-7 lg:order-2 order-1 relative">
          <div className="relative aspect-[5/4] rounded-sm overflow-hidden border border-arolena-line">
            <Image
              src={IMG}
              alt="Salón del Restaurante Arolena listo para clientes"
              fill
              sizes="(min-width: 1024px) 58vw, 100vw"
              className="object-cover editorial-img"
            />
          </div>
          <div
            aria-hidden="true"
            className="hidden lg:block absolute -top-6 -right-6 w-1/2 h-1/2 border border-arolena-gold/40 -z-0"
          />
        </div>
      </div>
    </section>
  );
}
