// Generated by GitHub Copilot
import Image from 'next/image';

const IMG = '/images/restaurante/IMG_2125.jpeg';

const ocasiones = [
  'Cenas en pareja',
  'Comidas familiares',
  'Grupos',
  'Reuniones de amigos',
  'Celebraciones',
  'Eventos',
  'Comidas y cenas de empresa'
];

export default function OccasionsSection() {
  return (
    <section id="ocasiones" className="bg-arolena-ink py-20 md:py-28">
      <div className="container grid lg:grid-cols-2 gap-12 lg:gap-16 items-center">
        <div>
          <p className="text-arolena-gold tracking-[0.3em] text-xs uppercase mb-4">
            Para cualquier ocasión
          </p>
          <h2 className="font-display text-4xl md:text-5xl text-arolena-cream">
            Un espacio versátil y elegante
          </h2>
          <p className="mt-6 text-arolena-cream/80 text-lg leading-relaxed">
            Desde una comida informal hasta una ocasión especial, Arolena
            ofrece un espacio cómodo, elegante y versátil para disfrutar en
            buena compañía.
          </p>
          <ul className="mt-8 flex flex-wrap gap-2">
            {ocasiones.map((o) => (
              <li
                key={o}
                className="text-sm px-4 py-2 rounded-full border border-arolena-line text-arolena-cream/85 bg-arolena-black/40"
              >
                {o}
              </li>
            ))}
          </ul>
        </div>

        <div className="relative aspect-[4/3] rounded-2xl overflow-hidden border border-arolena-line order-first lg:order-last">
          <Image
            src={IMG}
            alt="Salón del Restaurante Arolena listo para clientes"
            fill
            sizes="(min-width: 1024px) 50vw, 100vw"
            className="object-cover"
          />
        </div>
      </div>
    </section>
  );
}
