// Generated by GitHub Copilot
// Separador ornamental con motivo de diamante central — estilo editorial clásico.
interface OrnamentalDividerProps {
  className?: string;
}

export default function OrnamentalDivider({ className = '' }: OrnamentalDividerProps) {
  return (
    <div
      aria-hidden="true"
      className={`flex items-center justify-center gap-4 py-12 md:py-16 ${className}`}
    >
      <span className="h-px w-16 md:w-32 bg-gradient-to-r from-transparent to-arolena-gold/60" />
      <svg width="14" height="14" viewBox="0 0 14 14" className="text-arolena-gold">
        <path d="M7 0L14 7L7 14L0 7Z" fill="currentColor" opacity="0.9" />
      </svg>
      <span className="font-display-italic text-arolena-gold/70 text-xs tracking-[0.3em] uppercase">
        Arolena
      </span>
      <svg width="14" height="14" viewBox="0 0 14 14" className="text-arolena-gold">
        <path d="M7 0L14 7L7 14L0 7Z" fill="currentColor" opacity="0.9" />
      </svg>
      <span className="h-px w-16 md:w-32 bg-gradient-to-l from-transparent to-arolena-gold/60" />
    </div>
  );
}
