// Generated by GitHub Copilot
// Sección de filosofía / manifiesto con cita protagonista.
import Eyebrow from './Eyebrow';

export default function PhilosophySection() {
  return (
    <section
      id="filosofia"
      className="relative bg-arolena-black py-32 md:py-44 overflow-hidden"
    >
      {/* Aura dorada de fondo */}
      <div
        aria-hidden="true"
        className="absolute inset-0 bg-[radial-gradient(ellipse_60%_50%_at_50%_50%,rgba(200,168,118,0.07),transparent)]"
      />
      <span
        aria-hidden="true"
        className="absolute left-1/2 -translate-x-1/2 top-1/2 -translate-y-1/2 text-[20rem] md:text-[32rem] leading-none font-display-italic text-arolena-cream/[0.018] select-none pointer-events-none"
      >
        “
      </span>

      <div className="container relative max-w-4xl text-center">
        <Eyebrow number="—">Manifiesto</Eyebrow>
        <p className="mt-10 font-display text-3xl md:text-5xl leading-[1.15] text-arolena-cream">
          Cocinamos como{' '}
          <span className="font-display-italic text-arolena-gold">se cocinaba en casa</span>,
          con la pausa del horno de leña, la masa que reposa lo que tiene que reposar y el
          producto que llega <span className="font-display-italic text-arolena-gold">de cerca</span>.
        </p>
        <div className="mt-12 flex items-center justify-center gap-4">
          <span className="h-px w-12 bg-arolena-gold/60" />
          <span className="font-display-italic text-arolena-gold tracking-wide">
            La casa Arolena
          </span>
          <span className="h-px w-12 bg-arolena-gold/60" />
        </div>
      </div>
    </section>
  );
}
