// Generated by GitHub Copilot
// Barra de progreso dorada en la parte superior según el scroll vertical.
'use client';

import { useEffect, useState } from 'react';

export default function ScrollProgress() {
  const [progress, setProgress] = useState(0);

  useEffect(() => {
    const update = () => {
      const h = document.documentElement;
      const total = h.scrollHeight - h.clientHeight;
      setProgress(total > 0 ? (h.scrollTop / total) * 100 : 0);
    };
    update();
    window.addEventListener('scroll', update, { passive: true });
    window.addEventListener('resize', update);
    return () => {
      window.removeEventListener('scroll', update);
      window.removeEventListener('resize', update);
    };
  }, []);

  return (
    <div
      aria-hidden="true"
      className="fixed top-0 left-0 right-0 z-[60] h-[2px] bg-arolena-black/0 pointer-events-none"
    >
      <div
        className="h-full bg-gradient-to-r from-arolena-gold via-arolena-goldsoft to-arolena-gold transition-[width] duration-100"
        style={{ width: `${progress}%` }}
      />
    </div>
  );
}
