// Generated by GitHub Copilot
import { restaurantInfo } from '@/data/restaurantInfo';

const servicios = [
  {
    titulo: 'Restaurante',
    descripcion: 'Disfruta en nuestro salón o terraza con un ambiente cuidado y elegante.'
  },
  {
    titulo: 'Recogida en local',
    descripcion: 'Pide por teléfono o WhatsApp y recoge tu pedido en el restaurante.'
  },
  {
    titulo: 'Envío a domicilio',
    descripcion: 'Servicio propio en nuestras zonas de reparto.'
  },
  {
    titulo: 'Uber Eats',
    descripcion: 'Disponible en buena parte de Granada y alrededores.'
  }
];

export default function ServicesSection() {
  return (
    <section id="servicios" className="bg-arolena-black py-20 md:py-28">
      <div className="container">
        <div className="max-w-3xl">
          <span aria-hidden="true" className="gold-rule" />
          <p className="text-arolena-gold tracking-[0.3em] text-xs uppercase mb-4">
            Servicios
          </p>
          <h2 className="font-display text-4xl md:text-5xl text-arolena-cream">
            Disfruta Arolena como prefieras
          </h2>
          <p className="mt-4 text-arolena-cream/75">
            Disfruta Arolena en nuestro restaurante, pide para recoger o
            consulta disponibilidad de envío a domicilio.
          </p>
        </div>

        <div className="mt-12 grid sm:grid-cols-2 lg:grid-cols-4 gap-4">
          {servicios.map((s) => (
            <article
              key={s.titulo}
              className="card-hover rounded-2xl border border-arolena-line bg-arolena-ink p-6"
            >
              <h3 className="font-display text-xl text-arolena-cream">
                {s.titulo}
              </h3>
              <p className="mt-3 text-arolena-cream/75 text-sm leading-relaxed">
                {s.descripcion}
              </p>
            </article>
          ))}
        </div>

        <div className="mt-12 grid md:grid-cols-2 gap-6">
          <div className="rounded-2xl border border-arolena-line bg-arolena-ink p-6">
            <h3 className="font-display text-xl text-arolena-gold">
              Zonas de reparto propio
            </h3>
            <p className="mt-3 text-arolena-cream/85 text-sm leading-relaxed">
              {restaurantInfo.zonasReparto.join(' · ')}
            </p>
          </div>
          <div className="rounded-2xl border border-arolena-line bg-arolena-ink p-6">
            <h3 className="font-display text-xl text-arolena-gold">
              Zona aproximada en Uber Eats
            </h3>
            <p className="mt-3 text-arolena-cream/85 text-sm leading-relaxed">
              {restaurantInfo.zonasUberEats.join(' · ')}
            </p>
          </div>
        </div>
      </div>
    </section>
  );
}
