// Generated by GitHub Copilot
import Eyebrow from './Eyebrow';
import { restaurantInfo } from '@/data/restaurantInfo';

const servicios = [
  {
    titulo: 'Restaurante',
    descripcion: 'Disfruta en nuestro salón o terraza con un ambiente cuidado y elegante.'
  },
  {
    titulo: 'Recogida en local',
    descripcion: 'Pide por teléfono o WhatsApp y recoge tu pedido en el restaurante.'
  },
  {
    titulo: 'Envío a domicilio',
    descripcion: 'Servicio propio en nuestras zonas de reparto.'
  },
  {
    titulo: 'Uber Eats',
    descripcion: 'Disponible en buena parte de Granada y alrededores.'
  }
];

export default function ServicesSection() {
  return (
    <section id="servicios" className="bg-arolena-black py-24 md:py-36">
      <div className="container">
        <div className="max-w-3xl">
          <Eyebrow number="05">Servicios</Eyebrow>
          <h2 className="font-display text-5xl md:text-6xl text-arolena-cream leading-[0.95]">
            Disfruta Arolena{' '}
            <span className="font-display-italic text-arolena-gold">como prefieras</span>.
          </h2>
          <p className="mt-6 text-arolena-cream/75 max-w-xl">
            Disfruta Arolena en nuestro restaurante, pide para recoger o
            consulta disponibilidad de envío a domicilio.
          </p>
        </div>

        <div className="mt-14 grid sm:grid-cols-2 lg:grid-cols-4 gap-px bg-arolena-line">
          {servicios.map((s, i) => (
            <article
              key={s.titulo}
              className="card-hover bg-arolena-ink p-8 group"
            >
              <span className="font-display-italic text-arolena-gold/70 text-xl block mb-4">
                {String(i + 1).padStart(2, '0')}
              </span>
              <h3 className="font-display text-2xl text-arolena-cream group-hover:text-arolena-gold transition-colors">
                {s.titulo}
              </h3>
              <p className="mt-4 text-arolena-cream/70 text-sm leading-relaxed">
                {s.descripcion}
              </p>
            </article>
          ))}
        </div>

        <div className="mt-12 grid md:grid-cols-2 gap-6">
          <div className="rounded-2xl border border-arolena-line bg-arolena-ink p-6">
            <h3 className="font-display text-xl text-arolena-gold">
              Zonas de reparto propio
            </h3>
            <p className="mt-3 text-arolena-cream/85 text-sm leading-relaxed">
              {restaurantInfo.zonasReparto.join(' · ')}
            </p>
          </div>
          <div className="rounded-2xl border border-arolena-line bg-arolena-ink p-6">
            <h3 className="font-display text-xl text-arolena-gold">
              Zona aproximada en Uber Eats
            </h3>
            <p className="mt-3 text-arolena-cream/85 text-sm leading-relaxed">
              {restaurantInfo.zonasUberEats.join(' · ')}
            </p>
          </div>
        </div>
      </div>
    </section>
  );
}
