// Generated by GitHub Copilot
import Image from 'next/image';

const IMG = '/images/platos/IMG_1809.jpeg';

export default function WoodOvenSection() {
  return (
    <section id="horno" className="bg-arolena-ink py-20 md:py-28">
      <div className="container grid lg:grid-cols-2 gap-12 lg:gap-16 items-center">
        <div className="relative aspect-[4/3] rounded-2xl overflow-hidden border border-arolena-line">
          <Image
            src={IMG}
            alt="Pizza artesanal recién salida del horno de leña"
            fill
            sizes="(min-width: 1024px) 50vw, 100vw"
            className="object-cover"
          />
        </div>

        <div>
          <p className="text-arolena-gold tracking-[0.3em] text-xs uppercase mb-4">
            Nuestra firma
          </p>
          <h2 className="font-display text-4xl md:text-5xl text-arolena-cream">
            El sabor del horno de leña
          </h2>
          <p className="mt-6 text-arolena-cream/80 text-lg leading-relaxed">
            Nuestras pizzas se elaboran en horno de leña con masa artesanal
            preparada en el restaurante, consiguiendo una textura crujiente,
            aroma auténtico y sabor mediterráneo.
          </p>
          <ul className="mt-8 grid sm:grid-cols-2 gap-4 text-arolena-cream/85">
            <li className="flex items-start gap-3">
              <span aria-hidden="true" className="mt-1 h-2 w-2 rounded-full bg-arolena-gold" />
              Masa artesanal de elaboración propia
            </li>
            <li className="flex items-start gap-3">
              <span aria-hidden="true" className="mt-1 h-2 w-2 rounded-full bg-arolena-gold" />
              Cocción en horno de leña tradicional
            </li>
            <li className="flex items-start gap-3">
              <span aria-hidden="true" className="mt-1 h-2 w-2 rounded-full bg-arolena-gold" />
              Ingredientes seleccionados
            </li>
            <li className="flex items-start gap-3">
              <span aria-hidden="true" className="mt-1 h-2 w-2 rounded-full bg-arolena-gold" />
              Sabor auténticamente mediterráneo
            </li>
          </ul>
        </div>
      </div>
    </section>
  );
}
