// Generated by GitHub Copilot
import Image from 'next/image';
import Eyebrow from './Eyebrow';

const IMG = '/images/platos/IMG_1809.jpeg';

export default function WoodOvenSection() {
  return (
    <section id="horno" className="relative bg-arolena-ink py-24 md:py-36 overflow-hidden">
      {/* Número gigante de fondo */}
      <span
        aria-hidden="true"
        className="absolute -right-4 md:-right-12 top-8 text-[18rem] md:text-[28rem] leading-none font-display-italic text-arolena-cream/[0.025] select-none pointer-events-none"
      >
        01
      </span>

      <div className="container relative grid lg:grid-cols-12 gap-10 lg:gap-16 items-center">
        {/* Imagen rotada con marco offset */}
        <div className="lg:col-span-7 relative">
          <div className="relative aspect-[4/5] md:aspect-[5/4] rounded-sm overflow-hidden border border-arolena-line max-w-2xl">
            <Image
              src={IMG}
              alt="Pizza artesanal recién salida del horno de leña"
              fill
              sizes="(min-width: 1024px) 58vw, 100vw"
              className="object-cover editorial-img"
            />
          </div>
          {/* Marco dorado offset */}
          <div
            aria-hidden="true"
            className="hidden lg:block absolute -bottom-6 -left-6 w-2/3 h-2/3 border border-arolena-gold/40 -z-0"
          />
          <p className="mt-6 text-xs tracking-[0.3em] uppercase text-arolena-cream/50">
            Fig. 01 — Masa de larga fermentación
          </p>
        </div>

        <div className="lg:col-span-5">
          <Eyebrow number="01">Nuestra firma</Eyebrow>
          <h2 className="font-display text-5xl md:text-6xl text-arolena-cream leading-[0.95]">
            El sabor del{' '}
            <span className="font-display-italic text-arolena-gold">horno de leña</span>.
          </h2>
          <p className="mt-8 text-arolena-cream/80 text-lg leading-relaxed">
            Nuestras pizzas se elaboran en horno de leña con masa artesanal
            preparada en el restaurante, consiguiendo una textura crujiente,
            aroma auténtico y sabor mediterráneo.
          </p>
          <ul className="mt-10 space-y-4 text-arolena-cream/85 border-l border-arolena-line pl-6">
            <li className="flex items-baseline gap-3">
              <span className="text-arolena-gold font-display-italic text-sm">i.</span>
              Masa artesanal de elaboración propia
            </li>
            <li className="flex items-baseline gap-3">
              <span className="text-arolena-gold font-display-italic text-sm">ii.</span>
              Cocción en horno de leña tradicional
            </li>
            <li className="flex items-baseline gap-3">
              <span className="text-arolena-gold font-display-italic text-sm">iii.</span>
              Ingredientes seleccionados
            </li>
            <li className="flex items-baseline gap-3">
              <span className="text-arolena-gold font-display-italic text-sm">iv.</span>
              Sabor auténticamente mediterráneo
            </li>
          </ul>
        </div>
      </div>
    </section>
  );
}
