// Generated by GitHub Copilot
// Tipos compartidos para la carta. Preparado para futuras propiedades (alérgenos, imagen, opciones).

export interface MenuItem {
  id?: string;
  nombre: string;
  precio?: string;
  descripcion?: string;
  imagen?: string;
  alergenos?: string[];
  disponible?: boolean;
  recomendado?: boolean;
  vegetariano?: boolean;
  sinGlutenBajoConsulta?: boolean;
  opciones?: Array<{ nombre: string; precio?: string }>;
}

export interface MenuCategory {
  categoria: string;
  items: MenuItem[];
}

export interface Menu {
  carta: MenuCategory[];
}
