// Generated by GitHub Copilot
// Información central del restaurante. Punto único para futuras integraciones (CMS/backend).

export const restaurantInfo = {
  nombreComercial: 'Arolena',
  nombreCompleto: 'Restaurante Arolena Sabores Mediterráneos',
  ciudad: 'Albolote, Granada',
  direccion: 'Avenida Lucilo Carvajal 17, 18220 Albolote, Granada',
  telefono: '958 69 23 15',
  telefonoTel: '+34958692315',
  whatsapp: '+34630350179',
  whatsappDisplay: '630 35 01 79',
  whatsappLink:
    'https://wa.me/34630350179?text=Hola%2C%20me%20gustar%C3%ADa%20reservar%20mesa%20en%20Arolena',
  instagram: 'https://instagram.com/restaurante.arolena',
  instagramHandle: '@restaurante.arolena',
  tiktok: 'https://tiktok.com/@restaurante.arolena',
  tiktokHandle: '@restaurante.arolena',
  email: '',
  horario: {
    comidas: '12:00 – 16:30',
    cenas: '20:00 – 23:30',
    cierre: 'Cerrado los lunes'
  },
  cocinas: ['Mediterránea', 'Italiana', 'Parrilla'],
  servicios: [
    'Comer en restaurante',
    'Recogida en local',
    'Envío a domicilio',
    'Uber Eats'
  ],
  zonasReparto: [
    'Albolote',
    'Monteluz',
    'Torreón',
    'Villa Blanca',
    'Peligros',
    'Maracena',
    'Atarfe',
    'El Chaparral',
    'Cortijo del Aire',
    'Loma Verde',
    'Pantano del Cubillas'
  ],
  zonasUberEats: [
    'Albolote',
    'Maracena',
    'Juncaril',
    'Pulianas',
    'Granada norte',
    'Cartuja',
    'Almanjáyar',
    'La Chana',
    'Traumatología'
  ],
  accesibilidad: [
    'Acceso adaptado para personas con movilidad reducida',
    'Acceso con silla de ruedas'
  ],
  espacios: [
    'Zona interior',
    'Terraza sujeta a disponibilidad',
    'Espacio amplio y luminoso',
    'Ambiente moderno, cuidado y elegante'
  ],
  mascotas: 'Se permiten perros en terraza',
  formasPago: ['Efectivo', 'Tarjeta'],
  mapsEmbed:
    'https://www.google.com/maps?q=Avenida+Lucilo+Carvajal+17,+18220+Albolote,+Granada&output=embed',
  mapsLink:
    'https://www.google.com/maps/search/?api=1&query=Avenida+Lucilo+Carvajal+17,+18220+Albolote,+Granada'
} as const;

export type RestaurantInfo = typeof restaurantInfo;
